build:
	sudo docker-compose -p horror_api build

up:
	sudo docker-compose -p horror_api up

down:
	sudo docker-compose -p horror_api down

test:
	sudo docker-compose -p horror_api exec web python manage.py test
